FROM node:20-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

RUN mkdir /home/node/app/bot

COPY src/bot/package*.json /home/node/app/bot/
# COPY src/bot .

RUN chown -R node:node /home/node/app

WORKDIR /home/node/app/bot

RUN npm install -g nodemon

USER node

RUN npm install discord.js

CMD [ "npm", "run", "bot" ]
